version: "3.7"
services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./.env
        target: /slack-leaderboards/.env
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
